from mag import Mag
from unit import Unit, ComplexUnit
from real_values import Value

mag1000=Mag(
    [
        "Yotta",
        "Zetta",
        "Exa",
        "Peta",
        "Tera",
        "Giga",
        "Mega",
        "Kilo",
        "milli",
        "micro",
        "nano",
        "pico",
        "femto",
        "atto",
        "zepto",
        "yocto"
    ],
    [
        "Y",
        "Z",
        "E",
        "P",
        "T",
        "G",
        "M",
        "K",
        "m",
        "μ",
        "n",
        "p",
        "f",
        "a",
        "z",
        "y"
    ],
    [
        10**24,
        10**21,
        10**18,
        10**15,
        10**12,
        10**9,
        10**6,
        10**3,
        10**-3,
        10**-6,
        10**-9,
        10**-12,
        10**-15,
        10**-18,
        10**-21,
        10**-24
    ],
    delta_unit=1000
)

mag1024=Mag(
    [
        "Yobi",
        "Zebi",
        "Exbi",
        "Pebi",
        "Tebi",
        "Gibi",
        "Mebi",
        "Kibi",
    ],
    [
        "Yi",
        "Zi",
        "Ei",
        "Pi",
        "Ti",
        "Gi",
        "Mi",
        "Ki"
    ],
    [
        1024**8,
        1024**7,
        1024**6,
        1024**5,
        1024**4,
        1024**3,
        1024**2,
        1024
    ],
    delta_unit_top=1024
)

seconds=Unit(["second","seconds"],"s")
meter=Unit(["meter","meters"],"m")
gram=Unit(["gram","grams"],"g")
ampere=Unit(["ampere","amperes"],"A")
kelvine=Unit(["kelvin","kelvins"],"K")
candela=Unit("candela","cd")

bit=Unit(["bit","bits"],"b")
byte=Unit(["byte","bytes"],"B")

hertz=ComplexUnit({},{},"hertz","Hz")/seconds
newton=ComplexUnit({},{},"newton","N")*gram*meter/seconds/seconds
pascal=ComplexUnit({},{},"pascal","Pa")*newton/meter/meter
joule=ComplexUnit({},{},"joule","J")*newton*meter
watt=ComplexUnit({},{},"watt","W")*joule/seconds